// <auto-generated>
// Rewired Constants
// This list was generated on 04/06/2020 15:56:25
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // Movement
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "All keybinds related to movement", friendlyName = "Moves the player verticaly")]
        public const int MoveVert = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "All keybinds related to movement", friendlyName = "Moves the player horizontally")]
        public const int MoveHor = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "All keybinds related to movement", friendlyName = "Moves the player verticaly")]
        public const int MoveVerticalQwerty = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "All keybinds related to movement", friendlyName = "Moves the player horizontally")]
        public const int MoveHorizontalQwerty = 13;
        // Camera
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "All kebinds related to camera movement", friendlyName = "Travels the camera back and forth to an alternate angle")]
        public const int Camera_Travel = 5;
        // Mod
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "All keybinds that modify the game s state", friendlyName = "Puts the game into the main menu")]
        public const int Pause = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "All keybinds that modify the game s state", friendlyName = "Resets the current level")]
        public const int Reset = 7;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIHorizontal")]
        public const int UIHorizontal = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIVertical")]
        public const int UIVertical = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UISubmit")]
        public const int UISubmit = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UICancel")]
        public const int UICancel = 11;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Only player in scene, not supposed to be changed")]
        public const int CurrentPlayer = 0;
    }
    public static partial class CustomController {
    }
}
